apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

commonLabels:
  app: hello

namespace: the-namespace

resources:
- deployment.yaml
- service.yaml
- configMap.yaml
- ../global/configMap.yaml
- ../global/namespace.yaml
