namePrefix: prod-
commonLabels:
  variant: prod
  org: verint
commonAnnotations:
  note: Hello, I am prod!
namespace: prod
bases:
- ../../../base/app1
patchesStrategicMerge:
- increase_replicas.yaml
images:
- name: monopole/hello
  newTag: 2  