namePrefix: prod-
commonLabels:
  variant: prod
  org: verint
commonAnnotations:
  note: prod-nginx
namespace: prod
bases:
- ../../../base/app2
patchesStrategicMerge:
- configMap.yaml
# images:
# - name: nginx
#   newTag: "1.19"