apiVersion: v1
kind: Service
metadata:
  name: ngnix-app-service
  labels:
    app: ngnix-app
spec:
  type: LoadBalancer
  ports:
  - name: ngnix-app-http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ngnix-app